### ISSUE TITLE
大家好啊我是被引流的狗

### ISSUE THREAD

**Issue by WangNianyi2001** [haofanurusai/OttoKeyboard#1]
老板波形或者频谱存哪了啊，找半天没找着
[以及](https://github.com/haofanurusai/OttoKeyboard/blob/main/Input.ino#L51)，？

**Comment by haofanurusai** [comment]
波表见[WaveTable.h](https://github.com/haofanurusai/OttoKeyboard/blob/main/WaveTable.h)，用了PROGMEM关键字，让它存在Flash里，用pgm_read_byte_near()函数从Flash中取数
NOP在[第一行](https://github.com/haofanurusai/OttoKeyboard/blob/main/Input.ino#L1)有宏定义，调了AVR汇编的无操作指令
，一堆NOP起到延时作用，为了避免中断竞争，导致音频渲染被打断从而走音，把负责delay()、millis()等函数的Timer0关了，所以没用函数延时。【delayMicroseconds()不用定时器，但是这里以后要塞其它东西，先保持现状】
因为电气特性，行扫描电平到达按键是有延迟的，不加这个延时的话扫不上按键，加延时后，使得电平能够保持一段时间后达到稳定状态，之后再来读键
